//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.Chats = new HashSet<Chat>();
        }
    
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public int UserID { get; set; }
        public int SecondUserID { get; set; }
        public bool UserGet { get; set; }
        public bool SecondUserGet { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
    }
}